### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by AmaliaGM** [AmaliaGM/ReactGroupProject#25]
- There is one (1) person in this group.
- [Project link](https://github.com/AmaliaGM/ReactGroupProject/projects/1) 

## Project requirements

- Join a Zoom call with your team. Only one person needs to copy the board on behalf of the entire team but everybody should help during the call.
- Create an empty repository for your group project.
- Follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) in order to copy the [[TEMPLATE] React Group Project](https://github.com/microverseinc/curriculum-react-redux/projects/1) board.
- Open the GitHub project (Kanban board) in your team repo.
- Make sure that in the card titles you can see categories: Setup, Fetch data, Lists render, Actions, Conditional components, Filters.
- Make sure that each card starts with [Xpt] - that number indicates the number of points that shows how complex the task is. 1 point = 1 hour of work.
- If your group includes two people - remove all cards with Team3 in the title.
- Each of the team members should assign themselves to the cards from all categories (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.
- [Open a new issue in your repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue).
In its description, paste a link to your GitHub project.
Add a note telling the reviewer how many people there are in your team.
- Use the issue link to ask for a review. A Code Reviewer will leave you feedback in the issue's comment.

**Comment by ShahierNashaat** [comment]
Hi @AmaliaGM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 

- Your readme looks professional ✔️

## Required Changes ♻️
- [ ] Kindly make sure that all cards are assigned to team members.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AmaliaGM** [comment]
@ShahierNashaat Hello.. I am the only team member

**Comment by m05e5** [comment]
# Status: ✔️ Project Approved ✔️ 

Hello @AmaliaGM  🔥 

Good job on With your Kanban board. Well Done.
Your project is complete! There is nothing else to say other than... it's time to get to the next milestone :shipit:
Congratulations! 🎉

![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)

Now you can merge this branch 🚀 

_m05e5_

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AmaliaGM** [comment]
@m05e5 Thanks a lot! Happy Coding to you also!
